### ISSUE TITLE
task1_ai_ml_model : Initial research on Chatterbot as a tool for NLU development in the context of the project

### ISSUE THREAD

**Issue by nlauchande** [omdena/ptsd#2]
Goals of the task :

Research on : https://github.com/gunthercox/ChatterBot

- Execute a basic getting started tutorial

- Understand the architecture of a conversational NLP solution

- Analyse tradeoffs w/ Dialogflow

- Sketch a possible solution for a simple conversational bot

**Comment by markoke** [comment]
I could work with albert on this

**Comment by albertlai431** [comment]
Basic information so far: looks like just a regular chatbot with training, preprocessing, and deployment capabilities.

**License**
- BSD 3-clause license: must include copyright notice

**Docs**
- documentation (https://chatterbot.readthedocs.io/en/stable/) looks pretty good, lots of info and includes different adaptors and utilities

**Integrations**
- Django and flaks integration

Can't seem to find much from looking at the github and documentation, rasa and dialogflow look a lot more comprehensive but this could be a simpler solution.

**Comment by abhron** [comment]
These are some of the tradeoffs with Rasa

1)Rasa has a flexibility of choosing pipelines like tensorflow_embedding, spacy_sklearn etc which makes it more cutting edge.
Chatterbot has several logic adapters which make use of naive Bayesian classification algorithms to determine if an input statement meets a particular set of criteria. Naive Bayes works most of the times but not always. So, it loses the flexibility of changing it directly as per your needs.
2) Rasa comes with one of the beautiful, elegant and fast NLP library spaCy, which has evolved exponentially in recent years. You can't think of building a chatbot without doing lots of custom NLP for your enterprise level chatbot or any chatbot covering corner-cases.
ChatterBot uses the Natural Language Toolkit (NLTK) for various language processing functions.  NLTK is kind of father of all Python based NLP libraries but it was popular before new libraries starting coming into picture. Using NLTK is lesser productive than using spaCy and that's why Rasa takes an edge here.
3) Rasa documentation is way more professional and extensive than ChatterBot's documenation.
4) Rasa is also continuously growing and evolving. There are few existing bugs as well but they are working hard to make it a production grade library. Lots of enterprise are already using Rasa and have deployed that in production. I am sure some must have done it using ChatterBot.
5) Rasa NLU supports storing your models in the cloud like Amazon S3, Google Cloud Storage(GCS), Microsoft Azure Storage. This is a must use feature for a production level application.
6) A good feature of ChatterBot I feel is they provide you direct support for integration with Django. ChatterBot provides out of the box models and endpoints that allow you build ChatterBot powered Django applications. I don't think Rasa provides this.  This will only be helpful if you are building your application using Django framework.
7) Rasa provides you HTTP APIs for parsing, training, evaluating and deleting models. Not sure on ChatterBot's part.
8) Both of them support multiple languages but the list is a little bigger for ChatterBot as compared to Rasa but remember stability matters.
9) Rasa has beautifully separated the Rasa-NLU(Natural Language Understanding) for turning natural language into structured data and Rasa-Core framework for building conversational software, which includes Chat Bots.

**Comment by MamadouBousso** [comment]
ChatterBot
-Easily installed using pip ( a problem with the installation of pyYAML but just downgrade pip, complete the installation and upgrade pip)
- Have a corpus for 21 languages and people can contribute ( https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data ) 
-you easily can create your own training data and structure.
- Can connect to different database( to sqlite3 by default)
- Have a logic adapter parameter which can help to build responses: for example:
-- The MathematicalEvaluation adapter solves math problems that use basic operations.
-- The TimeLogicAdapter returns the current time when the input statement asks for it(https://chatterbot.readthedocs.io/en/stable/logic/)
-You can get a response from your chatbot and set up a loop that can be broken with an exception or some keys on the keyboard
- The training process multiple times to reinforce preferred responses to particular input statements. 
We can retain three main steps:
1)Create your chatbot(( Add some logic adapter, sql adapter, preprocessor, filters and a language corpus  if necessary)
2)Train your chatbot with your own text 
3) Get your response 
4) Repeat 2) and 3) in order to reinforce the response
5) Integrate with django for the web
-For training, chatbot creates a knowledge graph with the data set provided, so that the statement inputs and responses are correctly represented.
-ChatterBot supports the ability to have multiple concurrent conversations with different people at the same time.
-Chatterbot selects a response based on its ability to compare two statements with each other. There are a number of ways to do this, and ChatterBot comes with a handful of methods built-in representing various text-comparison algorithms designed to compare one statement to another.

**Comment by nlauchande** [comment]
Thanks for the great work on this  :  @albertlai431  @abhron  @MamadouBousso 

A couple of questions based on what i learned around Dialogflow and Rasa : 
1. Does chatterbot allow you to come up with your own models?

2.  Are there any builtin standard NLP/NLU models ( LSTMs, Transformers, etc.)?

3.  Frontend support : Does it support facebook, watsapp, twilio, etc. ?

**Comment by MamadouBousso** [comment]
For training I think that we need to use a natural language processing library and mix it with a chatterbot. NLTK(https://www.nltk.org/) can be a good choice.

**Comment by MamadouBousso** [comment]
And scikit-learn. I will propose a schema for that

**Comment by MamadouBousso** [comment]
In Chatterbot you can build your own training class. For built-in standard library, i think about the classic one like TensorFlow or Keras
![Diapositive1](https://user-images.githubusercontent.com/1431116/60769451-5a8e8c80-a0bf-11e9-9bd9-64408c4f125a.jpeg)
. I  imagine this first draft of architecture.

**Comment by SubmitCode** [comment]
is it just my impression that RASA seems to be more mature than chatterbot? I gues as times goes by we should decide for the tool so we can prototype. Maybe a poll?

**Comment by nlauchande** [comment]
@SubmitCode  : I think chatterbot at this point is out of the equation, we can re-open if needed .
